# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Get trips

on:
  workflow_dispatch:
  schedule:
    - cron: 50 */2 * * *

jobs:
  get-trips:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: 'npm'
      - run: npm ci
      - id: get-token
        name: Get access token
        run: npm run gh:get-token
        env:
          USER_ID: ${{ secrets.USER_ID }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          SECURE_TOKEN_KEY: ${{ secrets.SECURE_TOKEN_KEY }}
          LAST_ACCESS_TOKEN: ${{ secrets.LAST_ACCESS_TOKEN }}
      - id: get-trips
        name: Get trips
        run: npm run gh:get-trips
        env:
          USER_ID: ${{ secrets.USER_ID }}
          ACCESS_TOKEN: ${{ steps.get-token.outputs.accessToken }}
      - id: update-trips-file
        name: Update trips file
        run: npm run gh:update-trips-file '${{ steps.get-trips.outputs.trips }}'
      - uses: test-room-7/action-update-file@v1
        with:
          file-path: trips.json
          commit-msg: Update trips.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
