# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Update trips

on:
  workflow_dispatch:
  schedule:
    - cron: 50 * * * *

jobs:
  update-trips:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - id: get-token
        name: Get access token
        run: npm run gh:get-token
        env:
          USER_ID: ${{ secrets.USER_ID }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          SECURE_TOKEN_KEY: ${{ secrets.SECURE_TOKEN_KEY }}
          LAST_ACCESS_TOKEN: ${{ secrets.LAST_ACCESS_TOKEN }}
      - id: get-trips
        name: Get trips
        run: npm run gh:get-trips
        env:
          USER_ID: ${{ secrets.USER_ID }}
          ACCESS_TOKEN: ${{ steps.get-token.outputs.accessToken }}
      - id: update-trips-file
        name: Update trips file
        run: npm run gh:update-trips-file '${{ steps.get-trips.outputs.trips }}'
      - id: check-empty-file
        name: Interrupt workflow
        run: |
          set +e
          git diff --quiet trips.json
          DIFF_EXIT_CODE=$?
          set -e

          if [ $DIFF_EXIT_CODE -ne 0 ]; then
              echo "trips.json has changed"
              echo "do-commit=true" >> $GITHUB_OUTPUT
          else
              echo "trips.json has not changed"
              echo "do-commit=false" >> $GITHUB_OUTPUT
          fi
      - uses: test-room-7/action-update-file@v1
        if: steps.check-empty-file.outputs.do-commit == 'true'
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
        with:
          file-path: trips.json
          commit-msg: üì¶Ô∏è Update trips.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
